version: '3.3'

services:
    mariadb:
        build: mariadb/.
        container_name: mysql
        image: mariadb:mariadb
        container_name: mariadb
        volumes:
            - dbdata:/var/lib/mysql/
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - wp

    wordpress:
        build: wordpress/.
        depends_on:
            - mariadb
        container_name: wordpress
        image: wordpress:wordpress
        volumes:
            - wpdata:/var/www/html/
        ports:
            - "9000:80"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            WORDPRESS_DB_HOST: mariadb:3306
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_TABLE_PREFIX: wp_
        networks:
            - wp

    nginx:
        build: nginx/.
        depends_on:
            - wordpress
            - mariadb
            - adminer
            - website
        container_name: nginx
        image: nginx:nginx
        ports:
            - "443:443"
        restart: always
        volumes:
            - wpdata:/var/www/html/
        networks:
            - wp

    adminer:
        build: adminer/.
        depends_on:
            - wordpress
        container_name: adminer
        image: adminer:adminer
        environment: 
            ADMINER_DEFAULT_SERVER: mariadb
            ADMINER_DESIGN: galkaev
        restart: always
        networks:
            - wp
        ports: 
            - 8080:8080

    website:
        build: website/.
        depends_on:
            - wordpress
        container_name: website
        image: website:website
        restart: always
        networks:
            - wp
        ports: 
            - 1234:81

    grafana:
        build: grafana/.
        depends_on:
            - wordpress
        container_name: grafana
        image: grafana:grafana
        restart: always
        networks:
            - wp
        ports: 
            - 3000:3000
        volumes:
            - grafana-data:/var/lib/grafana

    # monica:
    #     image: monica
    #     depends_on:
    #         - wordpress
    #     container_name: monica
    #     restart: always
    #     networks:
    #         - wp
    #     ports: 
    #         - 3333:82
    #     environment:
    #         - APP_KEY=vukGuMtPwUmR7KTgtH4NNTKDsK8D+58SAtsDpaaGWkA
    #         - DB_HOST=mariadb
    #         - DB_USERNAME=wordpress
    #         - DB_PASSWORD=wordpress
    #     volumes:
    #         - monica-data:/var/www/html/storage

networks:
    wp:

volumes:
    dbdata:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: '/home/bmerchin/data/dbdata'
    wpdata:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: '/home/bmerchin/data/wpdata'
    grafana-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: '/home/bmerchin/data/grafana-data'
    monica-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: '/home/bmerchin/data/monica-data'