version: "3.3"

services:
  nginx:
    build: nginx/.
    image: nginx:nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wpdata:/var/www
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./nginx/conf.d:/etc/nginx
    env_file:
      - .env
    networks:
      - my_network

  wordpress:
    build: wordpress/.
    image: wordpress:wordpress
    container_name: wordpress
    restart: always
    ports:
      - "9000:80"
    volumes:
      - wpdata:/var/www
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - my_network

#   wordpress:
#     container_name: wordpress
#     image: wordpress:latest
#     volumes:
#       - wpdata2:/var/www/html/
#     ports:
#       - 8000:80
#     restart: always
#     environment:
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: wordpress
#       WORDPRESS_DB_PASSWORD: wordpress
#     networks:
#       - my_network



  mariadb:
    build: mariadb/.
    image: mariadb:mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3333:3306"
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my_network

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bmerchin/data/dbdata'
  wpdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bmerchin/data/wpdata'
  wpdata2:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bmerchin/data/wpdata2'

networks:
  my_network: