version: "3.3"

services:
  nginx:
    build: nginx/.
    image: nginx:nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wpdata:/var/www/bmerchin
      - ./nginx/conf.d:/etc/nginx/conf.d
    env_file:
      - .env
    networks:
      - my_network

  wordpress:
    build: wordpress/.
    image: wordpress:wordpress
    restart: always
    volumes:
      - wpdata:/var/www/bmerchin
    env_file:
      - .env
    networks:
      - my_network

  mariadb:
    build: mariadb/.
    image: mariadb:mariadb
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my_network

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bmerchin/data/dbdata'
  wpdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bmerchin/data/wpdata'

networks:
  my_network: