version: "3.3"

services:
  nginx:
    build: nginx/.
    restart: always
    ports:
      - "8080:80"
    networks:
      - my_network
  wordpress:
    depends_on:
      - mariadb
    build: wordpress/.
    restart: always
#    ports:
#      - "8081:80"
    volumes:
      - ./website:/var/www/bmerchin
    networks:
      - my_network
  mariadb:
    build: mariadb/.
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network: